"""Move category relationship from food to restaurant

Revision ID: 19c41da9574e
Revises: a40f765fe625
Create Date: 2025-08-26 16:09:27.509532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19c41da9574e'
down_revision = 'a40f765fe625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('foods_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('foods_ibfk_2'), 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###
