"""Convert restaurant category to many-to-many relationship

Revision ID: 3459aca7c95c
Revises: 19c41da9574e
Create Date: 2025-08-26 16:48:40.836001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3459aca7c95c'
down_revision = '19c41da9574e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_categories',
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('UTC_TIMESTAMP()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('restaurant_id', 'category_id')
    )
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('restaurants_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('restaurants_ibfk_1'), 'categories', ['category_id'], ['id'])

    op.drop_table('restaurant_categories')
    # ### end Alembic commands ###
