"""add field on boarding complete

Revision ID: 497c55f4395a
Revises: 3459aca7c95c
Create Date: 2025-08-26 17:06:18.997634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497c55f4395a'
down_revision = '3459aca7c95c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('onboarding_completed')

    # ### end Alembic commands ###
