"""change field relation to cascade

Revision ID: d99aac6a7433
Revises: b575e27e841e
Create Date: 2025-09-14 23:08:23.657926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99aac6a7433'
down_revision = 'b575e27e841e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('food_images_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'foods', ['food_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('food_ratings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('food_ratings_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('food_ratings_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'foods', ['food_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('foods_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('restaurant_categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('restaurant_categories_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('restaurant_categories_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('restaurant_ratings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('restaurant_ratings_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('restaurant_ratings_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reviews_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('reviews_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'foods', ['food_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_favorite_categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_favorite_categories_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_favorite_categories_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_favorite_categories_ibfk_1'), 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('user_favorite_categories_ibfk_2'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reviews_ibfk_2'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('reviews_ibfk_1'), 'foods', ['food_id'], ['id'])

    with op.batch_alter_table('restaurant_ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('restaurant_ratings_ibfk_2'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('restaurant_ratings_ibfk_1'), 'restaurants', ['restaurant_id'], ['id'])

    with op.batch_alter_table('restaurant_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('restaurant_categories_ibfk_1'), 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('restaurant_categories_ibfk_2'), 'restaurants', ['restaurant_id'], ['id'])

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('foods_ibfk_1'), 'restaurants', ['restaurant_id'], ['id'])

    with op.batch_alter_table('food_ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('food_ratings_ibfk_1'), 'foods', ['food_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('food_ratings_ibfk_2'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('food_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('food_images_ibfk_1'), 'foods', ['food_id'], ['id'])

    # ### end Alembic commands ###
